server:
  port: 6161
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devpr?useSSL=false
    username: root
    password: P@nk@jkolse06

spring.jpa:
  hibernate:
    ddl-auto: update
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  spring.mvc.pathmatch.matching-strategy : ANT_PATH_MATCHER



